### ISSUE TITLE
How to recover from a StopIteration

### ISSUE THREAD

**Issue by betesh** [openlogic/random-word#3]
I am getting this error.  It appears to be coming from `RandomWord.nouns.next`.  I assume it means I reached the end of the list.  what is the recommended way of recovering from it?

```
   StopIteration:
     iteration reached an end
```

I don't mind starting the list from the beginning again.  It's just not clear how to do that.

**Comment by toddthomas** [comment]
There's no high-level API to reset the iterators, but this low-level technique used in the specs works:
```ruby
RandomWord.instance_eval{ @nouns, @adjs = nil, nil }
```
